"""add 2022-23-24 league tier to clubs

Revision ID: f3944d727941
Revises: 112dca73c3d6
Create Date: 2024-10-17 15:13:02.519841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3944d727941'
down_revision: Union[str, None] = '112dca73c3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('league_2024_25', sa.String(length=255), nullable=True))
    op.add_column('clubs', sa.Column('league_2023_24', sa.String(length=255), nullable=True))
    op.add_column('clubs', sa.Column('league_2022_23', sa.String(length=255), nullable=True))
    op.drop_column('clubs', 'league')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('league', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('clubs', 'league_2022_23')
    op.drop_column('clubs', 'league_2023_24')
    op.drop_column('clubs', 'league_2024_25')
    # ### end Alembic commands ###
