"""update club data

Revision ID: e90e39bec44f
Revises: 7be607ed50a7
Create Date: 2025-05-08 17:11:14.762960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e90e39bec44f'
down_revision: Union[str, None] = '7be607ed50a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('logo_has_animal', sa.Boolean(), nullable=True))
    op.add_column('clubs', sa.Column('logo_has_winged_animal', sa.Boolean(), nullable=True))
    op.add_column('clubs', sa.Column('logo_has_person', sa.Boolean(), nullable=True))
    op.add_column('clubs', sa.Column('logo_has_football', sa.Boolean(), nullable=True))
    op.add_column('clubs', sa.Column('logo_has_crown', sa.Boolean(), nullable=True))
    op.add_column('clubs', sa.Column('logo_has_numbers', sa.Boolean(), nullable=True))
    op.add_column('clubs', sa.Column('num_stars_in_logo', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('num_colors_in_logo', sa.String(length=50), nullable=True))
    op.add_column('clubs', sa.Column('logo_has_red', sa.Boolean(), nullable=True))
    op.add_column('clubs', sa.Column('logo_has_blue', sa.Boolean(), nullable=True))
    op.add_column('clubs', sa.Column('logo_has_green', sa.Boolean(), nullable=True))
    op.add_column('clubs', sa.Column('logo_has_black', sa.Boolean(), nullable=True))
    op.add_column('clubs', sa.Column('domestic_cup_titles', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('domestic_cup_runner_up', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('domestic_supercup_titles', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('domestic_supercup_runner_up', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('legal_name', sa.String(length=255), nullable=True))
    op.add_column('clubs', sa.Column('foundation_year', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('most_valuable_player', sa.Float(), nullable=True))
    op.add_column('clubs', sa.Column('oldest_player', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('most_expensive_entry', sa.Float(), nullable=True))
    op.add_column('clubs', sa.Column('most_expensive_exit', sa.Float(), nullable=True))
    op.add_column('clubs', sa.Column('foreigners_count', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('stadium_name', sa.String(), nullable=True))
    op.add_column('clubs', sa.Column('total_market_value', sa.Float(), nullable=True))
    op.drop_column('clubs', 'has_winged_animal')
    op.drop_column('clubs', 'foreigners_number')
    op.drop_column('clubs', 'cup_titles')
    op.drop_column('clubs', 'has_person')
    op.drop_column('clubs', 'short_name')
    op.drop_column('clubs', 'stars_number')
    op.drop_column('clubs', 'has_color_green')
    op.drop_column('clubs', 'has_football')
    op.drop_column('clubs', 'national_supercup_runner_up')
    op.drop_column('clubs', 'net_transfer_record')
    op.drop_column('clubs', 'cup_runner_up')
    op.drop_column('clubs', 'has_crown')
    op.drop_column('clubs', 'has_animal')
    op.drop_column('clubs', 'colors_number')
    op.drop_column('clubs', 'national_supercup_titles')
    op.drop_column('clubs', 'has_numbers')
    op.drop_column('clubs', 'has_color_blue')
    op.drop_column('clubs', 'has_color_red')
    op.drop_column('clubs', 'has_color_black')
    op.drop_column('clubs', 'year_founded')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('year_founded', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('has_color_black', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('has_color_red', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('has_color_blue', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('has_numbers', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('national_supercup_titles', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('colors_number', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('clubs', sa.Column('has_animal', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('has_crown', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('cup_runner_up', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('net_transfer_record', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('national_supercup_runner_up', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('has_football', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('has_color_green', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('stars_number', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('short_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('clubs', sa.Column('has_person', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('cup_titles', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('foreigners_number', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clubs', sa.Column('has_winged_animal', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('clubs', 'total_market_value')
    op.drop_column('clubs', 'stadium_name')
    op.drop_column('clubs', 'foreigners_count')
    op.drop_column('clubs', 'most_expensive_exit')
    op.drop_column('clubs', 'most_expensive_entry')
    op.drop_column('clubs', 'oldest_player')
    op.drop_column('clubs', 'most_valuable_player')
    op.drop_column('clubs', 'foundation_year')
    op.drop_column('clubs', 'legal_name')
    op.drop_column('clubs', 'domestic_supercup_runner_up')
    op.drop_column('clubs', 'domestic_supercup_titles')
    op.drop_column('clubs', 'domestic_cup_runner_up')
    op.drop_column('clubs', 'domestic_cup_titles')
    op.drop_column('clubs', 'logo_has_black')
    op.drop_column('clubs', 'logo_has_green')
    op.drop_column('clubs', 'logo_has_blue')
    op.drop_column('clubs', 'logo_has_red')
    op.drop_column('clubs', 'num_colors_in_logo')
    op.drop_column('clubs', 'num_stars_in_logo')
    op.drop_column('clubs', 'logo_has_numbers')
    op.drop_column('clubs', 'logo_has_crown')
    op.drop_column('clubs', 'logo_has_football')
    op.drop_column('clubs', 'logo_has_person')
    op.drop_column('clubs', 'logo_has_winged_animal')
    op.drop_column('clubs', 'logo_has_animal')
    # ### end Alembic commands ###
