"""add local id to grids

Revision ID: 7be607ed50a7
Revises: f056f19a22f5
Create Date: 2025-03-27 11:37:12.563931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7be607ed50a7'
down_revision: Union[str, None] = 'f056f19a22f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grids', sa.Column('local_id', sa.Integer, nullable=True))

    op.execute("""UPDATE grids SET local_id = id""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grids', 'local_id')
    # ### end Alembic commands ###
