"""add foundation year to clubs

Revision ID: 112dca73c3d6
Revises: 856a4fd9cc88
Create Date: 2024-10-17 13:09:42.070475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112dca73c3d6'
down_revision: Union[str, None] = '856a4fd9cc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('year_founded', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'year_founded')
    # ### end Alembic commands ###
