"""add starting date to grids

Revision ID: c90a9ce31657
Revises: f3944d727941
Create Date: 2024-10-18 18:59:41.169464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90a9ce31657'
down_revision: Union[str, None] = 'f3944d727941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grids', sa.Column('starting_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grids', 'starting_date')
    # ### end Alembic commands ###
