"""add average age and short name to clubs

Revision ID: e2f1053d3669
Revises: d8e9860d07bd
Create Date: 2024-10-16 13:49:05.228844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f1053d3669'
down_revision: Union[str, None] = 'd8e9860d07bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('short_name', sa.String(length=255), nullable=True))
    op.add_column('clubs', sa.Column('average_age', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'average_age')
    op.drop_column('clubs', 'short_name')
    # ### end Alembic commands ###
