"""add uefa supercup, club world cup and best club award

Revision ID: f8b941651c99
Revises: 2e26e6ef8221
Create Date: 2024-11-06 13:37:44.652453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b941651c99'
down_revision: Union[str, None] = '2e26e6ef8221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('uefa_super_cup_titles', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('uefa_super_cup_runner_up', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('club_world_cup_titles', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('club_world_cup_runner_up', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('best_club_awards', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('best_club_runner_up', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('best_club_third_place', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'best_club_third_place')
    op.drop_column('clubs', 'best_club_runner_up')
    op.drop_column('clubs', 'best_club_awards')
    op.drop_column('clubs', 'club_world_cup_runner_up')
    op.drop_column('clubs', 'club_world_cup_titles')
    op.drop_column('clubs', 'uefa_super_cup_runner_up')
    op.drop_column('clubs', 'uefa_super_cup_titles')
    # ### end Alembic commands ###
