"""add rest of trasnfermarkt data to clubs

Revision ID: 761addfa3fc8
Revises: e2f1053d3669
Create Date: 2024-10-16 15:29:37.563464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761addfa3fc8'
down_revision: Union[str, None] = 'e2f1053d3669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('squad_size', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('foreigners_number', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('foreigners_percentage', sa.Float(), nullable=True))
    op.add_column('clubs', sa.Column('national_team_players', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('net_transfer_record', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'net_transfer_record')
    op.drop_column('clubs', 'national_team_players')
    op.drop_column('clubs', 'foreigners_percentage')
    op.drop_column('clubs', 'foreigners_number')
    op.drop_column('clubs', 'squad_size')
    # ### end Alembic commands ###
