"""change grids primary keys

Revision ID: 7be607ed50a7
Revises: f056f19a22f5
Create Date: 2025-03-27 11:37:12.563931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7be607ed50a7'
down_revision: Union[str, None] = 'f056f19a22f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grids', 'meta_condition_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    op.create_unique_constraint('uq_user_name', 'grids', ['id', 'meta_condition_id'])

    op.drop_constraint('id', 'grids', type_='primary')

    op.create_primary_key('pk_id_meta_condition_id', 'grids', ['id', 'meta_condition_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pk_id_meta_condition_id', 'grids', type_='primary')

    op.create_primary_key(None, 'grids', ['id'])

    op.drop_constraint('uq_user_name', 'grids', type_='unique')

    op.alter_column('grids', 'meta_condition_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
