"""Add 24-25 champions and europa league participation to clubs

Revision ID: c6e1ad47070a
Revises: f8b941651c99
Create Date: 2025-02-14 10:00:14.612642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e1ad47070a'
down_revision: Union[str, None] = 'f8b941651c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('champions_league_2024_25', sa.Boolean(), nullable=True))
    op.add_column('clubs', sa.Column('europa_league_2024_25', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'europa_league_2024_25')
    op.drop_column('clubs', 'champions_league_2024_25')
    # ### end Alembic commands ###
