"""add stadium capacity to clubs

Revision ID: d8e9860d07bd
Revises: 584f62b3cc11
Create Date: 2024-10-15 09:29:16.822390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e9860d07bd'
down_revision: Union[str, None] = '584f62b3cc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('stadium_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'stadium_capacity')
    # ### end Alembic commands ###
