POST http://localhost:5000/grid_generation_test_endpoint
Content-Type: application/json

{}

###

POST http://localhost:5000/grid_generation_test_endpoint?meta_condition_id=2
Content-Type: application/json

{}

###